spring:
  application:
    name: JOB-SCHEDULER
  banner:
    location: banner.txt
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  jpa:
    database: mysql
    open-in-view: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
