server:
  port: 8081
logging:
  config: classpath:logback-spring-dev.xml
spring:
  banner:
    location: banner.txt
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: SAMPLE-EXECUTOR
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
ideal:
  job:
    access-token: dasdassdfafd
    scheduler-addresses: 127.0.0.1:9904
    executor-pool:
      core-pool-size: 0
      maximum-pool-size: 5
      work-queue-size: 0