###
POST http://127.0.0.1:8804/executor/create
Content-Type: application/json

{
  "title": "示例执行器1",
  "appName": "test"
}

###
POST http://127.0.0.1:8804/executor/update
Content-Type: application/json

{
  "executorId": 134930081742061568,
  "appName": "SAMPLE-EXECUTOR",
  "title": "示例执行器"
}

###
DELETE http://127.0.0.1:8804/executor/delete/134930081742061568

###
GET http://127.0.0.1:8804/executor/query?page=1&size=10&appName=SAMPLE
