###
POST http://127.0.0.1:8804/worker/create
Content-Type: application/json

{
  "title": "示例执行器1",
  "appName": "test"
}

###
POST http://127.0.0.1:8804/worker/update
Content-Type: application/json

{
  "workerId": 134930081742061568,
  "appName": "SAMPLE-EXECUTOR",
  "title": "示例执行器"
}

###
DELETE http://127.0.0.1:8804/worker/delete/134930081742061568

###
GET http://127.0.0.1:8804/worker/query?page=1&size=10&appName=SAMPLE