server:
  port: 21001
eureka:
  client:
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
ribbon:
  # ribbon缓存时间
  server-list-refresh-interval: 2000
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: dev
  application:
    name: CMPT-JOB-SCHEDULER
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  jpa:
    database: mysql
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
        temp:
          use_jdbc_metadata_defaults: false