server:
  port: 21001
spring:
  banner:
    location: banner.txt
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: dev
  application:
    name: JOB-SCHEDULER
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  jpa:
    database: mysql
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
