### 新建任务
POST http://{{ip}}:{{port}}/job/create
Content-Type: application/json

{
  "autoStart": false,
  "workerId": 133924649984589824,
  "executeType": "HTTP_SCRIPT",
  "executorHandler": "demoJobHandler",
  "executeParam": "test",
  "routeStrategy": "CONSISTENT_HASH",
  "blockStrategy": "SERIAL",
  "cron": "0/30 * * * * ?",
  "retryCount": 0,
  "jobName": "test",
  "alarmEmail": "",
  "application": "",
  "tenantId": "",
  "bizType": "",
  "customTag": "",
  "businessId": ""
}

### 更新任务
POST http://{{ip}}:{{port}}/job/update
Content-Type: application/json

{
  "jobId": 133800657135075328,
  "workerId": 133799357949411328,
  "executorHandler": "",
  "executeParam": "",
  "routeStrategy": "WEIGHT_ROUND_ROBIN",
  "blockStrategy": "PARALLEL",
  "cron": "0 0/5 * * * ?",
  "retryCount": 0,
  "jobName": "",
  "alarmEmail": ""
}

### 删除任务
DELETE http://{{ip}}:{{port}}/job/remove/133800657135075328

### 查询
POST http://{{ip}}:{{port}}/job/query
Content-Type: application/json

{
  "workerId": 0,
  "jobName": "",
  "executorHandler": "",
  "jobStatus": 0,
  "application": "",
  "tenantId": "",
  "bizType": "",
  "customTag": "",
  "businessId": ""X
}

### 开启任务
PUT http://{{ip}}:{{port}}/job/enable/133925036980436992

### 关闭任务
PUT http://{{ip}}:{{port}}/job/disable/133800657135075328


### 触发任务
POST http://127.0.0.1:8804/job/trigger/133925036980436993