###
POST http://127.0.0.1:8804/executor/create
Content-Type: application/json

{
  "appName": "SAMPLE-EXECUTOR",
  "title": "示例执行器"
}

###
POST http://127.0.0.1:8804/executor/update
Content-Type: application/json

{
  "executorId": 133477976011440128,
  "appName": "SAMPLE-EXECUTOR",
  "title": "示例执行器"
}

###
POST http://127.0.0.1:8804/executor/delete
Content-Type: application/x-www-form-urlencoded

executorId=133468825940131840

###
POST  http://127.0.0.1:8804/executor/query?page=1&size=10
Content-Type: application/json

{
  "appName": "SAMPLE-EXECUTOR"
}
