###
POST http://{{ip}}:{{port}}/executor/create
Content-Type: application/json

{
  "appName": "SAMPLE-EXECUTOR",
  "title": "示例执行器"
}


###
POST  http://{{ip}}:{{port}}/executor/query?page=1&size=10
Content-Type: application/json

{
  "appName": "SAMPLE-EXECUTOR"
}
