### http script
POST http://{{ip}}:{{port}}/job/create
Content-Type: application/json

{
  "autoStart": true,
  "executorId": 131041968867246080,
  "executeType": "HTTP_SCRIPT",
  "executeParam": "GET https://www.baidu.com/",
  "routeStrategy": "RANDOM",
  "blockStrategy": "SERIAL",
  "cron": "0/10 * * * * ?"
}
