### http script
POST http://{{ip}}:{{port}}/job/create
Content-Type: application/json

{
  "autoStart": true,
  "workerId": 131360599572480000,
  "executeType": "HTTP_SCRIPT",
  "executeParam": "POST http://127.0.0.1:8804/executor/query?page=1&size=10\nContent-Type: application/json\n\n{\n  \"appName\": \"SAMPLE-EXECUTOR\"\n}",
  "routeStrategy": "RANDOM",
  "blockStrategy": "SERIAL",
  "cron": "0/10 * * * * ?"
}

###
POST http://{{ip}}:{{port}}/job/create
Content-Type: application/json

{
  "autoStart": false,
  "workerId": 133924649984589824,
  "executeType": "JOB_HANDLER",
  "executorHandler": "demoJobHandler",
  "executeParam": "test",
  "routeStrategy": "CONSISTENT_HASH",
  "blockStrategy": "SERIAL",
  "cron": "0/30 * * * * ?",
  "retryCount": 0,
  "jobName": "test",
  "alarmEmail": "",
  "application": "",
  "tenantId": "",
  "bizType": "",
  "customTag": "",
  "businessId": ""
}